### ISSUE TITLE
HumanEval Hinglish Translations Tracker

### ISSUE THREAD

**Issue by mrigankpawagi** [mrigankpawagi/HinglishEval#15]
Please select any of the unchecked HumanEval problems and verify its translation by visiting the corresponding link to the draft translation. **Make a PR for any changes.** If a translation is already good, or if you have made a PR for it, make sure you check the corresponding box.

> [!TIP]
> Translations should be in _conversational_ Hindi, i.e., the "Hinglish" that we are used to speaking in technical/academic contexts besides everyday life. We are not looking for a pure translation to Hindi.

> [!NOTE]
> If you are not fluent in Hindi and think you cannot contribute to this task, do not worry! There is a lot more to be done (details in our next meeting).

- [x] [0](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/0)
- [x] [1](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/1)
- [x] [2](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/2)
- [x] [3](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/3)
- [x] [4](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/4)
- [x] [5](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/5)
- [x] [6](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/6)
- [x] [7](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/7)
- [x] [8](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/8)
- [x] [9](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/9)
- [x] [10](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/10)
- [x] [11](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/11)
- [x] [12](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/12)
- [x] [13](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/13)
- [x] [14](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/14)
- [x] [15](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/15)
- [x] [16](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/16)
- [x] [17](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/17)
- [x] [18](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/18)
- [x] [19](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/19)
- [x] [20](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/20)
- [x] [21](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/21)
- [x] [22](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/22)
- [x] [23](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/23)
- [x] [24](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/24)
- [x] [25](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/25)
- [x] [26](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/26)
- [x] [27](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/27)
- [x] [28](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/28)
- [x] [29](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/29)
- [x] [30](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/30)
- [x] [31](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/31)
- [x] [32](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/32)
- [x] [33](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/33)
- [x] [34](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/34)
- [x] [35](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/35)
- [x] [36](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/36)
- [x] [37](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/37)
- [x] [38](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/38)
- [x] [39](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/39)
- [x] [40](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/40)
- [x] [41](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/41)
- [x] [42](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/42)
- [x] [43](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/43)
- [x] [44](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/44)
- [x] [45](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/45)
- [x] [46](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/46)
- [x] [47](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/47)
- [x] [48](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/48)
- [x] [49](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/49)
- [x] [50](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/50)
- [x] [51](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/51)
- [x] [52](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/52)
- [x] [53](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/53)
- [x] [54](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/54)
- [x] [55](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/55)
- [x] [56](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/56)
- [x] [57](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/57)
- [x] [58](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/58)
- [x] [59](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/59)
- [x] [60](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/60)
- [x] [61](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/61)
- [x] [62](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/62)
- [x] [63](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/63)
- [x] [64](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/64)
- [x] [65](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/65)
- [x] [66](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/66)
- [x] [67](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/67)
- [x] [68](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/68)
- [x] [69](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/69)
- [x] [70](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/70)
- [x] [71](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/71)
- [x] [72](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/72)
- [x] [73](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/73)
- [x] [74](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/74)
- [x] [75](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/75)
- [x] [76](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/76)
- [x] [77](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/77)
- [x] [78](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/78)
- [x] [79](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/79)
- [x] [80](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/80)
- [x] [81](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/81)
- [x] [82](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/82)
- [x] [83](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/83)
- [x] [84](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/84)
- [x] [85](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/85)
- [x] [86](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/86)
- [x] [87](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/87)
- [x] [88](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/88)
- [x] [89](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/89)
- [x] [90](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/90)
- [x] [91](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/91)
- [x] [92](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/92)
- [x] [93](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/93)
- [x] [94](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/94)
- [x] [95](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/95)
- [x] [96](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/96)
- [x] [97](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/97)
- [x] [98](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/98)
- [x] [99](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/99)
- [x] [100](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/100)
- [x] [101](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/101)
- [x] [102](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/102)
- [x] [103](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/103)
- [x] [104](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/104)
- [x] [105](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/105)
- [x] [106](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/106)
- [x] [107](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/107)
- [x] [108](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/108)
- [x] [109](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/109)
- [x] [110](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/110)
- [x] [111](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/111)
- [x] [112](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/112)
- [x] [113](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/113)
- [x] [114](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/114)
- [x] [115](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/115)
- [x] [116](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/116)
- [x] [117](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/117)
- [x] [118](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/118)
- [x] [119](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/119)
- [x] [120](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/120)
- [x] [121](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/121)
- [x] [122](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/122)
- [x] [123](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/123)
- [x] [124](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/124)
- [x] [125](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/125)
- [x] [126](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/126)
- [x] [127](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/127)
- [x] [128](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/128)
- [x] [129](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/129)
- [x] [130](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/130)
- [x] [131](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/131)
- [x] [132](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/132)
- [x] [133](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/133)
- [x] [134](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/134)
- [x] [135](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/135)
- [x] [136](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/136)
- [x] [137](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/137)
- [x] [138](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/138)
- [x] [139](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/139)
- [x] [140](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/140)
- [x] [141](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/141)
- [x] [142](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/142)
- [x] [143](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/143)
- [x] [144](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/144)
- [x] [145](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/145)
- [x] [146](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/146)
- [x] [147](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/147)
- [x] [148](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/148)
- [x] [149](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/149)
- [x] [150](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/150)
- [x] [151](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/151)
- [x] [152](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/152)
- [x] [153](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/153)
- [x] [154](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/154)
- [x] [155](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/155)
- [x] [156](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/156)
- [x] [157](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/157)
- [x] [158](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/158)
- [x] [159](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/159)
- [x] [160](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/160)
- [x] [161](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/161)
- [x] [162](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/162)
- [x] [163](https://github.com/mrigankpawagi/MultilingualBenchmarking/blob/main/translation/drafts/163)
